import {ClerkProvider} from "@clerk/nextjs"
import { dark } from "@clerk/themes" 
import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PostGen AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: dark,
    }}
    >
    <html lang="en">
      <body
        className={`${inter.className} bg-black text-white antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
